---
title: "Variorum of Statistical Methods for Research Workers"
author: "Jonas Moss"
date: '2018-09-12'
slug: smrw-variorum
tags:
- history
- philosophy
categories:
- statistics
---
[*Statistical Methods for Research Workers*](https://en.wikipedia.org/wiki/Statistical_Methods_for_Research_Workers) (1924, henceforth *SMRW*) was Fisher's first book. Its' a textbook for practicing scientist, and probably the most important book on practical statistics book published. It went through 14 editions from 1924 to 1970. 

The book is obviously of pure historical interest, and it should be illuminating in itself to read the perstives of Fisher. An interesting application of SMRW, is to track changes in Fisher's thought by looking at the changes in editions of SMRW. An example of this can be found in Lehmann's [*Fisher, Neyman, and the Creation of Classical Statistics*](https://www.springer.com/us/book/9781441994998). In section 4.4 he tracks Fisher's thought on the evidential interpretation of *p*-values. In presentations of the Neyman-Fisher debate, it's often said that Neyman prefered fixed significance levels while Fisher wanted us to interpret a *p*-value directly as an evidential measure (e.g., a *p*-value at 0.001 is stronger evidence against $H_0$ than a *p*-value of 0.049). According to Lehmann's reading of SMRW, Fisher settled on this interpretation long after they had a falling out in 1935. Indeed, when Fisher talks about *p*-values in the early editions of SMRW, he cares exclusively about the $0.05$ threshold. But in 1958 he changed a sentence from supporting the idea of fixed significance levels to the evidentiary interpretation. 

Lehmann's example is the following. In the 1926 edition of SMRW Fisher wrote,
> If P is between .1 and .9 there is certainly no reason to suspect the hypothesis tested. If it is below .02 it is strongly indicated that the hypothesis fails to account for the whole of the facts. We shall not often be astray if we draw a conventional line at .05 and consider that higher values of $\chi^2$ indicate a real discrepancy.

But in 1958 he changed this into

> The actual value of P obtainable from the table by interpolation indicates the strength of the evidence against the hypothesis. A value of $\chi^2$ exceeding the 5 per cent. point is seldom to be disregarded.

The interested reader will have troubles verifying Lehmann's claim, as she won't have access to all 14 editions of SMRW. In addition, if she were to obtain them, the toil of going through them all would be immense. Moreover, she would have a hard time finding other interesting evolutions of thought in SMRW if she so wished.

## Variorum

A *variorum* is a special edition of a book (or collection of books, structured in a way so that you can track changes between editions. It's often done with the Bible, and Kant's *Kritik der Reinen Vernuft* is always a variorum --- even Pax's Norwegian edition is a variorum edition. Darwin's *On the Origin of Species* had six editions (that become progressively *worse*), and there's a [variorum edition](https://www.amazon.com/Origin-Species-Variorum-Text-Reprint/dp/0812219546/ref=sr_1_1?s=books&ie=UTF8&qid=1536737684&sr=1-1&keywords=origin+of+species+variorum&dpID=51gClcG8qgL&preST=_SY291_BO1,204,203,200_QL40_&dpSrc=srch) for this one as well.

Even Fisher has been subject to variorumization. Henry Bennett edited a variorum edition of Fisher's [*The Genetical Theory of Natural Selection*](https://www.amazon.com/Genetical-Theory-Natural-Selection/dp/0198504403), (1930) his important book in population genetics. This was *maybe* easier to do than a variorum of SMRW, as it only had two editions. Still, it's publicaton created renewed interest in the work and review by several important geneticists.

## Proposal
Collect all editions of SMRW and make a variorum.
